apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-server
  template:
    metadata:
      labels:
        app: core-server
    spec:
      containers:
        - name: core-server
          image: core/server
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: development
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:8080;https://0.0.0.0:8081"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ASPNETCORE_HTTPS_PORTS
              value: "8081"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              value: asus
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /aspnetapp.pfx
            - name: connectionString
              value: "Host=core-database;Port=5432;Database=coredb;User ID=postgres;Password=;"
          ports:
            - containerPort: 8080
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: core-server
spec:
  type: LoadBalancer
  selector:
    app: core-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8081
      targetPort: 8081